import React from 'react';
import ReactDOM from 'react-dom';
import App from './containers/App/App';

// First thing to do during the initialization:
// programmatically create a div into the body of the html file
// to attach the main container component.
//
// Remember that there isn't an html file actually, it's generated by the
// html-webpack-plugin.
const root = document.createElement('div');
document.body.appendChild(root);

// Render the main app component.
ReactDOM.render(<App />, root);
